export const ATTENDANCE_CREATE_REQUEST = 'ATTENDANCE_CREATE_REQUEST';
export const ATTENDANCE_CREATE_SUCCESS = 'ATTENDANCE_CREATE_SUCCESS';
export const ATTENDANCE_CREATE_FAIL = 'ATTENDANCE_CREATE_FAIL';