export const ATTENDANCE_CREATE_REQUEST = 'ATTENDANCE_CREATE_REQUEST';
export const ATTENDANCE_CREATE_SUCCESS = 'ATTENDANCE_CREATE_SUCCESS';
export const ATTENDANCE_CREATE_FAIL = 'ATTENDANCE_CREATE_FAIL';

export const ATTENDANCE_CREATE_ORGANISATION_REQUEST = 'ATTENDANCE_CREATE_ORGANISATION_REQUEST';
export const ATTENDANCE_CREATE_ORGANISATION_SUCCESS = 'ATTENDANCE_CREATE_ORGANISATION_SUCCESS';
export const ATTENDANCE_CREATE_ORGANISATION_FAIL = 'ATTENDANCE_CREATE_ORGANISATION_FAIL';

export const ATTENDANCE_EDIT_REQUEST = 'ATTENDANCE_EDIT_REQUEST';
export const ATTENDANCE_EDIT_SUCCESS = 'ATTENDANCE_EDIT_SUCCESS';
export const ATTENDANCE_EDIT_FAIL = 'ATTENDANCE_EDIT_FAIL';

export const ATTENDANCE_DELETE_REQUEST = 'ATTENDANCE_DELETE_REQUEST';
export const ATTENDANCE_DELETE_SUCCESS = 'ATTENDANCE_DELETE_SUCCESS';
export const ATTENDANCE_DELETE_FAIL = 'ATTENDANCE_DELETE_FAIL';

export const ATTENDANCE_GET_PARTICIPANT_REQUEST = 'ATTENDANCE_GET_PARTICIPANT_REQUEST';
export const ATTENDANCE_GET_PARTICIPANT_SUCCESS = 'ATTENDANCE_GET_PARTICIPANT_SUCCESS';
export const ATTENDANCE_GET_PARTICIPANT_FAIL = 'ATTENDANCE_GET_PARTICIPANT_FAIL';