export const ATTENDANCE_CREATE_REQUEST = 'ATTENDANCE_CREATE_REQUEST';
export const ATTENDANCE_CREATE_SUCCESS = 'ATTENDANCE_CREATE_SUCCESS';
export const ATTENDANCE_CREATE_FAIL = 'ATTENDANCE_CREATE_FAIL';

export const ATTENDANCE_GET_PARTICIPANT_REQUEST = 'ATTENDANCE_GET_PARTICIPANT_REQUEST';
export const ATTENDANCE_GET_PARTICIPANT_SUCCESS = 'ATTENDANCE_GET_PARTICIPANT_SUCCESS';
export const ATTENDANCE_GET_PARTICIPANT_FAIL = 'ATTENDANCE_GET_PARTICIPANT_FAIL';