export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST';
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_CREATE_FAIL = 'COURSE_CREATE_FAIL';

export const COURSE_ADD_PARTICIPANT_REQUEST = 'COURSE_ADD_PARTICIPANT_REQUEST';
export const COURSE_ADD_PARTICIPANT_SUCCESS = 'COURSE_ADD_PARTICIPANT_SUCCESS';
export const COURSE_ADD_PARTICIPANT_FAIL = 'COURSE_ADD_PARTICIPANT_FAIL';

export const COURSE_GET_ALL_REQUEST = 'COURSE_GET_ALL_REQUEST';
export const COURSE_GET_ALL_SUCCESS = 'COURSE_GET_ALL_SUCCESS';
export const COURSE_GET_ALL_FAIL = 'COURSE_GET_ALL_FAIL';

export const COURSE_GET_ONE_REQUEST = 'COURSE_GET_ONE_REQUEST';
export const COURSE_GET_ONE_SUCCESS = 'COURSE_GET_ONE_SUCCESS';
export const COURSE_GET_ONE_FAIL = 'COURSE_GET_ONE_FAIL';